version: '3.8'

services:
  front:
    build:
      context: next/.
      target: development
    ports:
      - "1285:1285"
    volumes:
      - ./next:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    tty: true