version: '3.8'

services:
  front:
    build:
      context: next/.
    ports:
      - "1285:1285"
    volumes:
      - ./next:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    tty: true

volumes:
  node_modules: