name: nextjs-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: docker compose run --rm front sh -c "npm install"

      - name: Build
        run: docker compose run --rm front sh -c "npm run build"

      - name: Add nojekyll
        run: |
          cd next
          mkdir -p next/out
          touch next/out/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'next/out'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
